### ISSUE TITLE
Suggestion: Auto-generate image classes in backgrounds.styl

### ISSUE THREAD

**Issue by BenJenkinson** [lynnandtonic/airport-codes#169]
It's slightly tedious to add the four different lines in backgrounds.styl for each airport code that is added. 

Could we generate them somehow? Perhaps with:

```stylus
$extension = jpg

$images = {
 'a': 'alice',
 'b': 'bob',
 'c': 'charlie'
}

.card
  for $code, $photographer in $images
    &.{$code} { background-image: url(card/$code\-$photographer.$extension) }

.small
  for $code, $photographer in $images
    &.{$code} { background-image: url(small/$code\-$photographer.$extension) }
```

To give:

```css
.card.a {
  background-image: url("card/a-alice.jpg");
}
.card.b {
  background-image: url("card/b-bob.jpg");
}
.card.c {
  background-image: url("card/c-charlie.jpg");
}
.small.a {
  background-image: url("small/a-alice.jpg");
}
.small.b {
  background-image: url("small/b-bob.jpg");
}
.small.c {
  background-image: url("small/c-charlie.jpg");
}
```

~~I haven't made this a pull request since the downside to doing it this way is I can't figure how to call the existing variables like `$lax` to give "lax-photographer.jpg" by constructing the variable `$lax` from `$ + "lax"` in the loop.~~

I read some more of the Stylus documentation, and discovered [hashes](http://learnboost.github.io/stylus/docs/hashes.html). That would let us store the code, and the photographer's name separately, but combine them to generate the file-names.
